# Connection Pool, javax.mail
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@192.168.0.214:1521:xe
      username: ENC(UnNfpd0gJ1Lma/8BH/ulZw==)
      password: ENC(Od9fYj1m3KO7o7mxsiJfIw==)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(F9LrJ47J7s/ZhRY1ElfHcikVcKpPirbDCW1jtr+Hnso=)
    password: ENC(+vqwbhnQzr6ntqsq1hBWc/e6EB9vWJEw2331dhXRFbI=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  main:
#    web-application-type: none  # Do not use embeded tomcat

# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml

# character encoding, session, port
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
      tracking-modes: cookie

# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor